//! File export logic for Flow type declarations.

use crate::{Config, Flow, TypeVisitor};
use std::any::TypeId;
use std::collections::HashSet;
use std::path::Path;

/// Export error.
#[derive(Debug, thiserror::Error)]
pub enum ExportError {
    #[error("type `{0}` cannot be exported")]
    CannotBeExported(&'static str),
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Fmt(#[from] std::fmt::Error),
}

/// Write a Flow type declaration to a file.
pub fn export_to<T: Flow + 'static + ?Sized>(cfg: &Config, path: &Path) -> Result<(), ExportError> {
    let content = export_to_string::<T>(cfg)?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let type_name = T::ident(cfg);

    // If file exists, merge declarations (append if not duplicate)
    if path.exists() {
        let existing = std::fs::read_to_string(path)?;
        let marker = format!("type {type_name}");

        if existing.contains(&marker) {
            // Already exported -- skip
            return Ok(());
        }

        // Append the declaration portion to existing file
        let decl_part = extract_declaration_part(&content);
        let mut merged = existing;
        merged.push('\n');
        merged.push_str(&decl_part);
        std::fs::write(path, merged)?;
    } else {
        std::fs::write(path, content)?;
    }

    Ok(())
}

/// Export `T` together with all of its dependencies.
pub fn export_all_into<T: Flow + ?Sized + 'static>(cfg: &Config) -> Result<(), ExportError> {
    let mut seen = HashSet::new();
    export_recursive::<T>(cfg, &mut seen)
}

struct Visit<'a> {
    cfg: &'a Config,
    seen: &'a mut HashSet<TypeId>,
    error: Option<ExportError>,
}

impl TypeVisitor for Visit<'_> {
    fn visit<T: Flow + 'static + ?Sized>(&mut self) {
        if self.error.is_some() || <T as crate::Flow>::output_path().is_none() {
            return;
        }
        self.error = export_recursive::<T>(self.cfg, self.seen).err();
    }
}

fn export_recursive<T: Flow + ?Sized + 'static>(
    cfg: &Config,
    seen: &mut HashSet<TypeId>,
) -> Result<(), ExportError> {
    if !seen.insert(TypeId::of::<T>()) {
        return Ok(());
    }

    let relative = <T as crate::Flow>::output_path()
        .ok_or(ExportError::CannotBeExported(std::any::type_name::<T>()))?;
    let path = cfg.out_dir().join(relative);
    export_to::<T>(cfg, &path)?;

    let mut visitor = Visit {
        cfg,
        seen,
        error: None,
    };
    <T as crate::Flow>::visit_dependencies(&mut visitor);

    if let Some(e) = visitor.error {
        Err(e)
    } else {
        Ok(())
    }
}

/// Render the full file content for type `T` as a string.
pub fn export_to_string<T: Flow + ?Sized + 'static>(cfg: &Config) -> Result<String, ExportError> {
    let mut content = String::from("// @flow\n// Generated by flowjs-rs. Do not edit.\n\n");

    // Collect and emit import statements for dependencies (deduplicated)
    let self_id = TypeId::of::<T>();
    let deps = T::dependencies(cfg);
    let mut seen_imports = HashSet::new();
    for dep in &deps {
        if dep.type_id == self_id || !seen_imports.insert(dep.type_id) {
            continue;
        }
        let import_path = dep
            .output_path
            .to_str()
            .unwrap_or(&dep.flow_name);
        content.push_str(&format!(
            "import type {{ {} }} from './{import_path}';\n",
            dep.flow_name
        ));
    }
    if seen_imports.iter().next().is_some() {
        content.push('\n');
    }

    if let Some(docs) = T::docs() {
        content.push_str("/**\n");
        for line in docs.lines() {
            content.push_str(&format!(" * {line}\n"));
        }
        content.push_str(" */\n");
    }

    let decl = T::decl(cfg);
    // Opaque types already include `declare export` in their decl
    if decl.starts_with("declare export") {
        content.push_str(&format!("{decl}\n"));
    } else {
        content.push_str(&format!("export {decl}\n"));
    }

    Ok(content)
}

/// Extract only the declaration portion (after the header) from a full export string.
fn extract_declaration_part(content: &str) -> String {
    // Skip the "// @flow\n// Generated by...\n\n" header lines
    let mut result = String::new();
    let mut past_header = false;
    for line in content.lines() {
        if past_header {
            result.push_str(line);
            result.push('\n');
        } else if line.is_empty() {
            past_header = true;
        }
    }
    result
}
