include = ["**/*.toml"]
exclude = ["target/**"]

[formatting]
align_entries = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
column_width = 100
compact_arrays = true
compact_inline_tables = true
indent_string = "  "
reorder_keys = false
