//! File export logic for Flow type declarations.

use crate::{Config, ExportError, Flow};
use std::path::Path;

/// Write a Flow type declaration to a file.
pub fn export_to<T: Flow + 'static + ?Sized>(cfg: &Config, path: &Path) -> Result<(), ExportError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let decl = T::decl(cfg);
    let mut content = String::from("// @flow\n// Generated by flowjs-rs. Do not edit.\n\n");

    if let Some(docs) = T::docs() {
        content.push_str("/**\n");
        for line in docs.lines() {
            content.push_str(&format!(" * {line}\n"));
        }
        content.push_str(" */\n");
    }

    content.push_str(&format!("export {decl}\n"));

    // If file exists, merge declarations (append if not duplicate)
    if path.exists() {
        let existing = std::fs::read_to_string(path)?;
        let type_name = T::name(cfg);
        let marker = format!("type {type_name}");

        if existing.contains(&marker) {
            // Already exported — skip
            return Ok(());
        }

        // Append to existing file
        let mut merged = existing;
        merged.push('\n');
        if let Some(docs) = T::docs() {
            merged.push_str("/**\n");
            for line in docs.lines() {
                merged.push_str(&format!(" * {line}\n"));
            }
            merged.push_str(" */\n");
        }
        merged.push_str(&format!("export {decl}\n"));
        std::fs::write(path, merged)?;
    } else {
        std::fs::write(path, content)?;
    }

    Ok(())
}
