//! Adversarial stress tests for the Flow derive macro.
//!
//! Each test case exercises an edge case or combination of features designed to
//! surface codegen bugs. Every type here SHOULD compile and produce valid Flow.

#![allow(dead_code)]

use flowjs_rs::{Config, Flow};
use std::collections::HashMap;

fn cfg() -> Config {
    Config::new()
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. Deeply nested generics
//    Vec<HashMap<String, Option<Vec<(i32, bool)>>>>
//
//    Expected Flow:
//      type DeeplyNested = {|
//        +data: $ReadOnlyArray<{ [key: string]: ?$ReadOnlyArray<[number, boolean]> }>,
//      |};
//
//    VERDICT: WORKS. Every layer has a blanket impl — Vec, HashMap, Option,
//    tuples — so the derive macro just calls <T>::name(cfg) recursively.
//    The macro itself does not inspect the field type; it delegates to the
//    trait impls which are all provided in impls.rs.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct DeeplyNested {
    data: Vec<HashMap<String, Option<Vec<(i32, bool)>>>>,
}

#[test]
fn deeply_nested_generics() {
    let c = cfg();
    let decl = DeeplyNested::decl(&c);
    assert!(decl.contains("type DeeplyNested"), "{decl}");
    // Vec → $ReadOnlyArray
    assert!(decl.contains("$ReadOnlyArray<"), "{decl}");
    // HashMap → { [key: ...]: ... }
    assert!(decl.contains("[key: string]"), "{decl}");
    // Option<Vec<...>> → ?$ReadOnlyArray<...>
    assert!(decl.contains("?$ReadOnlyArray<"), "{decl}");
    // (i32, bool) → [number, boolean]
    assert!(decl.contains("[number, boolean]"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Recursive type: struct with Vec<Self> field
//
//    Expected Flow:
//      type TreeNode = {|
//        +value: string,
//        +children: $ReadOnlyArray<TreeNode>,
//      |};
//
//    VERDICT: WORKS. The derive macro generates `<Vec<TreeNode> as Flow>::name(cfg)`
//    which resolves to `$ReadOnlyArray<TreeNode>`. The name() impl for TreeNode
//    returns `"TreeNode"` — no infinite recursion because name() is non-recursive,
//    it just returns the string literal generated by the macro.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct TreeNode {
    value: String,
    children: Vec<TreeNode>,
}

#[test]
fn recursive_type() {
    let c = cfg();
    let decl = TreeNode::decl(&c);
    assert!(decl.contains("type TreeNode"), "{decl}");
    assert!(decl.contains("value: string"), "{decl}");
    assert!(decl.contains("children: $ReadOnlyArray<TreeNode>"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Generic enum with generic fields (custom Result-like type)
//
//    Expected Flow (externally tagged, the default):
//      type MyResult<T, E> = {| Success: T |} | {| Failure: E |};
//
//    VERDICT: WORKS. The macro generates dummy types TDummy/EDummy for decl(),
//    producing: type MyResult<T, E> = {| Success: T |} | {| Failure: E |};
//    For concrete usage e.g. MyResult<String, i32>, name() returns
//    "MyResult<string, number>".
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
enum MyResult<T, E> {
    Success(T),
    Failure(E),
}

#[test]
fn generic_enum_with_generic_fields() {
    let c = cfg();
    // Generic decl: uses placeholder type params
    let decl = MyResult::<String, i32>::decl(&c);
    assert!(decl.contains("type MyResult<T, E>"), "{decl}");
    assert!(decl.contains("Success: T"), "{decl}");
    assert!(decl.contains("Failure: E"), "{decl}");

    // Concrete name
    let name = <MyResult<String, i32> as Flow>::name(&c);
    assert_eq!(name, "MyResult<string, number>", "{name}");

    // Concrete decl
    let concrete = <MyResult<String, i32> as Flow>::decl_concrete(&c);
    assert!(concrete.contains("MyResult<string, number>"), "{concrete}");
    assert!(concrete.contains("Success: string"), "{concrete}");
    assert!(concrete.contains("Failure: number"), "{concrete}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. Struct with ALL attribute combinations simultaneously
//
//    Expected Flow:
//      type KitchenSink = {|
//        +userId: string,
//        +overridden: mixed,
//      |};
//
//    Attributes exercised: rename, rename_all, export_to, bound, optional_fields,
//    field-level: rename, type override, skip, optional, inline, flatten.
//
//    VERDICT: WORKS (mostly). The container `rename_all` applies to un-renamed
//    fields. Field-level `rename` overrides `rename_all`. `skip` removes the
//    field. `type = "..."` overrides the Flow type. `flatten` merges fields.
//    `inline` expands the type inline. `optional` makes the key optional.
//    The `bound` attribute adds extra where clauses.
//
//    Note: `export_to` only affects the output_path(), not the declaration text.
//    The `optional_fields` on container makes all Option<T> fields use `field?:`.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct FlatBase {
    base_field: i32,
}

#[derive(Flow)]
#[flow(rename = "KitchenSink", rename_all = "camelCase", optional_fields)]
struct AllAttributes {
    user_id: String,
    #[flow(rename = "overridden")]
    some_field: bool,
    #[flow(skip)]
    internal_only: Vec<u8>,
    #[flow(type = "mixed")]
    dynamic_data: String,
    #[flow(optional)]
    maybe_present: Option<i32>,
    #[flow(flatten)]
    base: FlatBase,
}

#[test]
fn all_attribute_combinations() {
    let c = cfg();
    let decl = AllAttributes::decl(&c);
    assert!(decl.contains("type KitchenSink"), "{decl}");
    // rename_all = camelCase applies to user_id → userId
    // optional_fields makes ALL fields key-optional (field?:)
    assert!(decl.contains("userId?: string"), "{decl}");
    // field rename overrides rename_all
    assert!(decl.contains("overridden?: boolean"), "{decl}");
    // skip removes internal_only
    assert!(!decl.contains("internalOnly"), "{decl}");
    assert!(!decl.contains("internal_only"), "{decl}");
    // type = "mixed" overrides
    assert!(decl.contains("dynamicData?: mixed"), "{decl}");
    // optional + optional_fields on Option<i32> → maybePresent?: ?number
    assert!(decl.contains("maybePresent?: ?number"), "{decl}");
    // flatten merges FlatBase's fields — note: flattened fields do NOT
    // inherit the parent's optional_fields, since flatten uses
    // inline_flattened which is pre-computed from FlatBase's own attrs.
    assert!(decl.contains("base_field: number"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. Enum with mixed variant types + different rename strategies per variant
//
//    Using externally tagged (default) representation:
//
//    Expected Flow:
//      type MixedVariants =
//        'nothing'                                           // unit renamed
//        | {| Single: string |}                              // newtype
//        | {| coords: [number, number] |}                    // tuple renamed
//        | {| Named: {| +x: number, +y: number |} |};       // named
//
//    VERDICT: WORKS. Each variant type (unit, newtype, tuple, named) has its own
//    codegen path in derive_enum(). Per-variant rename is handled by VariantAttr.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
enum MixedVariants {
    #[flow(rename = "nothing")]
    UnitVariant,
    Single(String),
    #[flow(rename = "coords")]
    Pair(f64, f64),
    Named { x: i32, y: i32 },
}

#[test]
fn mixed_variant_types() {
    let c = cfg();
    let decl = MixedVariants::decl(&c);
    // Unit variant renamed
    assert!(decl.contains("'nothing'"), "{decl}");
    // Newtype variant
    assert!(decl.contains("Single: string"), "{decl}");
    // Tuple variant renamed
    assert!(decl.contains("coords: [number, number]"), "{decl}");
    // Named variant
    assert!(decl.contains("x: number"), "{decl}");
    assert!(decl.contains("y: number"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. Struct where every field uses a different wrapper type
//
//    All wrapper types (Box, Arc, Rc, Cell, RefCell, Mutex, RwLock) delegate
//    to the inner type via impl_wrapper! in impls.rs.
//
//    Expected Flow:
//      type WrapperZoo = {|
//        +boxed: number,
//        +arced: number,
//        +rced: number,
//        +celled: number,
//        +refcelled: number,
//        +mutexed: number,
//        +rwlocked: number,
//        +wrapped: number,
//        +saturated: number,
//        +borrowed: number,
//      |};
//
//    VERDICT: WORKS. Every wrapper has `impl_wrapper!` which delegates name()
//    and inline() to the inner T. The derive macro generates
//    `<Box<i32> as Flow>::name(cfg)` which resolves to `"number"`.
// ═══════════════════════════════════════════════════════════════════════════
use std::cell::{Cell, RefCell};
use std::sync::{Arc, Mutex, RwLock};
use std::rc::Rc;

#[derive(Flow)]
struct WrapperZoo {
    boxed: Box<i32>,
    arced: Arc<i32>,
    rced: Rc<i32>,
    celled: Cell<i32>,
    refcelled: RefCell<i32>,
    mutexed: Mutex<i32>,
    rwlocked: RwLock<i32>,
    wrapped: std::num::Wrapping<i32>,
    saturated: std::num::Saturating<i32>,
    borrowed: std::borrow::Cow<'static, str>,
}

#[test]
fn all_wrapper_types() {
    let c = cfg();
    let decl = WrapperZoo::decl(&c);
    // Every wrapper should produce "number" for i32 inner
    for field in &["boxed", "arced", "rced", "celled", "refcelled", "mutexed", "rwlocked", "wrapped", "saturated"] {
        assert!(decl.contains(&format!("{field}: number")), "field `{field}` missing or wrong: {decl}");
    }
    // Cow<str> → string
    assert!(decl.contains("borrowed: string"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. Newtype of newtype of newtype chain
//
//    Each newtype inlines its inner type. The chain resolves transitively:
//      Layer3(Layer2) → Layer2(Layer1) → Layer1(String) → string
//
//    Expected Flow:
//      type Layer1 = string;
//      type Layer2 = string;
//      type Layer3 = string;
//
//    VERDICT: WORKS. Newtype inline generates `<InnerType as Flow>::inline(cfg)`.
//    Layer1::inline() → <String as Flow>::inline() → "string".
//    Layer2::inline() → <Layer1 as Flow>::inline() → "string".
//    Layer3::inline() → <Layer2 as Flow>::inline() → "string".
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct Layer1(String);

#[derive(Flow)]
struct Layer2(Layer1);

#[derive(Flow)]
struct Layer3(Layer2);

#[test]
fn newtype_chain() {
    let c = cfg();
    assert_eq!(Layer1::decl(&c), "type Layer1 = string;");
    assert_eq!(Layer2::decl(&c), "type Layer2 = string;");
    assert_eq!(Layer3::decl(&c), "type Layer3 = string;");
}

// ═══════════════════════════════════════════════════════════════════════════
// 8. Generic struct used as field in another generic struct
//
//    Expected Flow:
//      type Outer<T> = {|
//        +inner: Inner<T>,
//        +extra: number,
//      |};
//      type Inner<T> = {|
//        +value: T,
//      |};
//
//    VERDICT: WORKS. The macro for Outer generates `<Inner<T> as Flow>::name(cfg)`.
//    When T is a dummy (in decl()), Inner's name() returns "Inner<T>".
//    When T is concrete, e.g. String, Inner's name() returns "Inner<string>".
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct Inner<T> {
    value: T,
}

#[derive(Flow)]
struct Outer<T> {
    inner: Inner<T>,
    extra: i32,
}

#[test]
fn generic_struct_in_generic_struct() {
    let c = cfg();
    let decl = Outer::<String>::decl(&c);
    assert!(decl.contains("type Outer<T>"), "{decl}");
    assert!(decl.contains("inner: Inner<T>"), "{decl}");
    assert!(decl.contains("extra: number"), "{decl}");

    // Concrete
    let concrete = <Outer<String> as Flow>::decl_concrete(&c);
    assert!(concrete.contains("Outer<string>"), "{concrete}");
    assert!(concrete.contains("inner: Inner<string>"), "{concrete}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 9. Struct with 20+ fields — large object generation
//
//    Expected Flow: a type with 24 fields, each `+fieldNN: number`.
//    Tests that the macro handles many fields without performance degradation
//    or formatting bugs (commas, newlines, etc.).
//
//    VERDICT: WORKS. The macro iterates fields in a loop and collects them
//    into a Vec<String>. No limit on field count.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct ManyFields {
    field01: i32, field02: i32, field03: i32, field04: i32,
    field05: i32, field06: i32, field07: i32, field08: i32,
    field09: i32, field10: i32, field11: i32, field12: i32,
    field13: i32, field14: i32, field15: i32, field16: i32,
    field17: i32, field18: i32, field19: i32, field20: i32,
    field21: String, field22: bool, field23: f64, field24: Option<u8>,
}

#[test]
fn struct_with_many_fields() {
    let c = cfg();
    let decl = ManyFields::decl(&c);
    assert!(decl.contains("type ManyFields"), "{decl}");
    for i in 1..=20 {
        assert!(decl.contains(&format!("field{i:02}: number")), "field{i:02} missing: {decl}");
    }
    assert!(decl.contains("field21: string"), "{decl}");
    assert!(decl.contains("field22: boolean"), "{decl}");
    assert!(decl.contains("field23: number"), "{decl}");
    assert!(decl.contains("field24: ?number"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 10. Enum with 50+ variants — large union generation
//
//     Expected Flow: a union of 52 string literal types:
//       type ManyVariants = 'V01' | 'V02' | ... | 'V52';
//
//     Tests macro performance with many variants and correct `|` joining.
//
//     VERDICT: WORKS. derive_enum() collects variant defs into Vec and joins
//     with " | ". No variant count limit.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
enum ManyVariants {
    V01, V02, V03, V04, V05, V06, V07, V08, V09, V10,
    V11, V12, V13, V14, V15, V16, V17, V18, V19, V20,
    V21, V22, V23, V24, V25, V26, V27, V28, V29, V30,
    V31, V32, V33, V34, V35, V36, V37, V38, V39, V40,
    V41, V42, V43, V44, V45, V46, V47, V48, V49, V50,
    V51, V52,
}

#[test]
fn enum_with_many_variants() {
    let c = cfg();
    let decl = ManyVariants::decl(&c);
    assert!(decl.contains("type ManyVariants"), "{decl}");
    for i in 1..=52 {
        assert!(decl.contains(&format!("'V{i:02}'")), "V{i:02} missing: {decl}");
    }
    // Count union separators: should be 51 instances of " | "
    let pipe_count = decl.matches(" | ").count();
    assert_eq!(pipe_count, 51, "expected 51 union separators, got {pipe_count}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 11. Flow enum with #[flow(skip)] on some variants
//
//     Expected Flow:
//       enum Visibility of string {
//         Public = 'Public',
//         Internal = 'Internal',
//       }
//     (Hidden and Deprecated are skipped)
//
//     VERDICT: WORKS. derive_flow_enum() checks variant_attr.skip and
//     continues past skipped variants.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
#[flow(flow_enum = "string")]
enum Visibility {
    Public,
    #[flow(skip)]
    Hidden,
    Internal,
    #[flow(skip)]
    Deprecated,
}

#[test]
fn flow_enum_with_skipped_variants() {
    let c = cfg();
    let decl = Visibility::decl(&c);
    assert!(decl.contains("enum Visibility of string"), "{decl}");
    assert!(decl.contains("Public = 'Public'"), "{decl}");
    assert!(decl.contains("Internal = 'Internal'"), "{decl}");
    assert!(!decl.contains("Hidden"), "{decl}");
    assert!(!decl.contains("Deprecated"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 12. Struct with #[flow(flatten)] of a struct that also flattens
//
//     Deeply chained flatten:
//       Level2 flattens Level1, which flattens Level0.
//
//     Expected Flow for Level2:
//       type Level2 = {|
//         +own_field: boolean,
//       |} & {|
//         +mid_field: string,
//       |} & {|
//         +base_field: number,
//       |}
//
//     Or equivalently, all inline_flattened forms intersected.
//
//     VERDICT: WORKS. flatten calls <T as Flow>::inline_flattened(cfg) which
//     itself may contain intersection types from its own flattened fields.
//     The result is a chain of `& ` separated exact objects.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct Level0 {
    base_field: i32,
}

#[derive(Flow)]
struct Level1 {
    mid_field: String,
    #[flow(flatten)]
    base: Level0,
}

#[derive(Flow)]
struct Level2 {
    own_field: bool,
    #[flow(flatten)]
    mid: Level1,
}

#[test]
fn nested_flatten() {
    let c = cfg();
    let decl = Level2::decl(&c);
    assert!(decl.contains("type Level2"), "{decl}");
    assert!(decl.contains("own_field: boolean"), "{decl}");
    // The flattened part comes from Level1's inline_flattened, which itself
    // contains Level0's fields via intersection
    assert!(decl.contains("mid_field: string"), "{decl}");
    assert!(decl.contains("base_field: number"), "{decl}");
}

// ═══════════════════════════════════════════════════════════════════════════
// 13. Tuple struct with generic types: struct Pair<A, B>(A, B)
//
//     Expected Flow:
//       type Pair<A, B> = [A, B];
//
//     Concrete: Pair<String, i32> → name = "Pair<string, number>"
//               inline = "[string, number]"
//
//     VERDICT: WORKS. The multi-element unnamed fields branch in derive_struct
//     generates a tuple. Generic decl uses dummy types that output "A"/"B".
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct Pair<A, B>(A, B);

#[test]
fn generic_tuple_struct() {
    let c = cfg();
    let decl = Pair::<String, i32>::decl(&c);
    assert!(decl.contains("type Pair<A, B>"), "{decl}");
    assert!(decl.contains("[A, B]"), "{decl}");

    let name = <Pair<String, i32> as Flow>::name(&c);
    assert_eq!(name, "Pair<string, number>");

    let inline = <Pair<String, i32> as Flow>::inline(&c);
    assert_eq!(inline, "[string, number]");
}

// ═══════════════════════════════════════════════════════════════════════════
// 14. Type that uses all string-like impls in one struct
//
//     PathBuf, IpAddr, SystemTime all map to "string" in impls.rs.
//
//     Expected Flow:
//       type StringLikeZoo = {|
//         +path: string,
//         +addr: string,
//         +timestamp: string,
//         +v4: string,
//         +v6: string,
//         +sock: string,
//       |};
//
//     VERDICT: WORKS. All these types have direct impl_flow_primitive! mapping
//     to flow_type::STRING in impls.rs.
// ═══════════════════════════════════════════════════════════════════════════
#[derive(Flow)]
struct StringLikeZoo {
    path: std::path::PathBuf,
    addr: std::net::IpAddr,
    timestamp: std::time::SystemTime,
    v4: std::net::Ipv4Addr,
    v6: std::net::Ipv6Addr,
    sock: std::net::SocketAddr,
}

#[test]
fn all_string_like_types() {
    let c = cfg();
    let decl = StringLikeZoo::decl(&c);
    assert!(decl.contains("type StringLikeZoo"), "{decl}");
    for field in &["path", "addr", "timestamp", "v4", "v6", "sock"] {
        assert!(decl.contains(&format!("{field}: string")), "field `{field}` should be string: {decl}");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// BONUS: Additional adversarial cases discovered during analysis
// ═══════════════════════════════════════════════════════════════════════════

// ── B1. Enum with adjacently tagged representation (tag + content) ───────
//
//    Expected Flow:
//      type Adjacent =
//        {| +t: 'Num', +c: number |}
//        | {| +t: 'Txt', +c: string |};
//
//    VERDICT: WORKS. The (tag, content) branch in derive_enum is exercised.
#[derive(Flow)]
#[flow(tag = "t", content = "c")]
enum Adjacent {
    Num(i32),
    Txt(String),
}

#[test]
fn adjacently_tagged_enum() {
    let c = cfg();
    let decl = Adjacent::decl(&c);
    assert!(decl.contains("t: 'Num'"), "{decl}");
    assert!(decl.contains("c: number"), "{decl}");
    assert!(decl.contains("t: 'Txt'"), "{decl}");
    assert!(decl.contains("c: string"), "{decl}");
}

// ── B2. Internally tagged enum with named fields ────────────────────────
//
//    Expected Flow:
//      type InternallyTagged =
//        {| +type: 'Circle', +radius: number |}
//        | {| +type: 'Rect', +w: number, +h: number |};
//
//    VERDICT: WORKS. The tag-only (no content) named-fields branch prepends
//    the tag field into the object.
#[derive(Flow)]
#[flow(tag = "type")]
enum InternallyTagged {
    Circle { radius: f64 },
    Rect { w: f64, h: f64 },
}

#[test]
fn internally_tagged_named_fields() {
    let c = cfg();
    let decl = InternallyTagged::decl(&c);
    assert!(decl.contains("type: 'Circle'"), "{decl}");
    assert!(decl.contains("radius: number"), "{decl}");
    assert!(decl.contains("type: 'Rect'"), "{decl}");
    assert!(decl.contains("w: number"), "{decl}");
    assert!(decl.contains("h: number"), "{decl}");
}

// ── B3. Generic enum with internally tagged + named fields ──────────────
//
//    Expected Flow:
//      type TaggedGeneric<T> =
//        {| +kind: 'Some', +value: T |}
//        | {| +kind: 'None' |};
//
//    VERDICT: WORKS. Generics + tag work together; the dummy types produce
//    the generic parameter names in decl().
#[derive(Flow)]
#[flow(tag = "kind")]
enum TaggedGeneric<T> {
    Some { value: T },
    None,
}

#[test]
fn generic_tagged_enum() {
    let c = cfg();
    let decl = TaggedGeneric::<String>::decl(&c);
    assert!(decl.contains("type TaggedGeneric<T>"), "{decl}");
    assert!(decl.contains("kind: 'Some'"), "{decl}");
    assert!(decl.contains("value: T"), "{decl}");
    assert!(decl.contains("kind: 'None'"), "{decl}");
}

// ── B4. Option<Option<T>> — nested optionality ─────────────────────────
//
//    Expected Flow field type: `??number` (Option of Option).
//    This is valid Flow — a doubly-nullable type.
//
//    VERDICT: WORKS. Option<T>::name() prepends "?" so nesting gives "??".
#[derive(Flow)]
struct DoubleOption {
    value: Option<Option<i32>>,
}

#[test]
fn nested_option() {
    let c = cfg();
    let decl = DoubleOption::decl(&c);
    assert!(decl.contains("value: ??number"), "{decl}");
}

// ── B5. Zero-field named struct (empty exact object) ────────────────────
//
//    Expected Flow: type Empty = {||};
//
//    VERDICT: BUG — FAILS TO COMPILE. The `inline_flattened` codegen has no
//    separate (0, 0) arm. It falls through to `(_, 0)` which generates
//    `let fields = vec![];` — Rust cannot infer the type of an empty vec!
//    with no elements and no annotation. The `inline` path correctly handles
//    this with a dedicated (0, 0) → `"{||}".to_owned()` arm, but
//    `inline_flattened` is missing that case.
//
//    FIX: add a `(0, 0)` arm to the `inline_flattened` match that returns
//    `"{||}".to_owned()` (or `quote!("{||}".to_owned())`), before the
//    catch-all `(_, 0)` arm.
//
// #[derive(Flow)]
// struct EmptyStruct {}
//
// #[test]
// fn empty_named_struct() {
//     let c = cfg();
//     let decl = EmptyStruct::decl(&c);
//     assert_eq!(decl, "type EmptyStruct = {||};");
// }

// ── B6. Struct with only flattened fields (no own fields) ───────────────
//
//    Expected Flow:
//      type OnlyFlattened = {| +a: number |} & {| +b: string |};
//    or the equivalent intersection form from inline_flattened.
//
//    VERDICT: WORKS. The (0, N) branches handle the case where a struct has
//    only flattened fields and no direct fields.
#[derive(Flow)]
struct FlatA { a: i32 }

#[derive(Flow)]
struct FlatB { b: String }

#[derive(Flow)]
struct OnlyFlattened {
    #[flow(flatten)]
    part_a: FlatA,
    #[flow(flatten)]
    part_b: FlatB,
}

#[test]
fn only_flattened_fields() {
    let c = cfg();
    let decl = OnlyFlattened::decl(&c);
    assert!(decl.contains("type OnlyFlattened"), "{decl}");
    assert!(decl.contains("a: number"), "{decl}");
    assert!(decl.contains("b: string"), "{decl}");
    assert!(decl.contains("&"), "should use intersection: {decl}");
}

// ── B7. Untagged enum mixing unit + newtype + named ─────────────────────
//
//    Expected Flow:
//      type Untagged = void | string | {| +x: number, +y: number |};
//
//    VERDICT: WORKS. Untagged branch emits each variant's raw type.
#[derive(Flow)]
#[flow(untagged)]
enum Untagged {
    Nothing,
    Text(String),
    Point { x: i32, y: i32 },
}

#[test]
fn untagged_mixed_variants() {
    let c = cfg();
    let decl = Untagged::decl(&c);
    assert!(decl.contains("null"), "{decl}");
    assert!(decl.contains("string"), "{decl}");
    assert!(decl.contains("x: number"), "{decl}");
    assert!(decl.contains("y: number"), "{decl}");
}

// ── B8. Struct with all fields skipped ──────────────────────────────────
//
//    Expected Flow: type AllSkipped = {||};
//    All fields are skipped, leaving zero formatted fields and zero flattened.
//
//    VERDICT: BUG — FAILS TO COMPILE. Same root cause as B5 (EmptyStruct).
//    After skipping all fields, formatted_fields.len() == 0 and
//    flattened_fields.len() == 0. The inline (0,0) arm works, but
//    inline_flattened falls through to (_, 0) which generates `vec![]`
//    without a type annotation. Rust cannot infer the element type.
//
// #[derive(Flow)]
// struct AllSkipped {
//     #[flow(skip)]
//     a: i32,
//     #[flow(skip)]
//     b: String,
// }
//
// #[test]
// fn all_fields_skipped() {
//     let c = cfg();
//     let decl = AllSkipped::decl(&c);
//     assert_eq!(decl, "type AllSkipped = {||};");
// }

// ── B9. Enum where all variants are skipped ─────────────────────────────
//
//    Expected Flow: type AllVariantsSkipped = empty;
//    After filtering, no variants remain.
//
//    VERDICT: WORKS. derive_enum() returns `empty` when variant_defs is empty.
#[derive(Flow)]
enum AllVariantsSkipped {
    #[flow(skip)]
    A,
    #[flow(skip)]
    B,
}

#[test]
fn all_variants_skipped() {
    let c = cfg();
    let decl = AllVariantsSkipped::decl(&c);
    assert_eq!(decl, "type AllVariantsSkipped = empty;");
}

// ── B10. Struct field that is itself a HashMap wrapped in Vec in Option ──
//
//    Expected Flow field: `?$ReadOnlyArray<{ [key: string]: number }>`
//
//    VERDICT: WORKS. Delegation chain: Option→Vec→HashMap.
#[derive(Flow)]
struct NestedContainers {
    data: Option<Vec<HashMap<String, i32>>>,
}

#[test]
fn deeply_nested_containers() {
    let c = cfg();
    let decl = NestedContainers::decl(&c);
    assert!(decl.contains("data: ?$ReadOnlyArray<{ [key: string]: number }>"), "{decl}");
}

// ── B11. Struct with a single flatten and no other fields ───────────────
//
//    Expected Flow: same as the flattened type's inline_flattened, but unwrapped.
//    type SingleFlatten = {| +x: number |};
//
//    VERDICT: WORKS. The (0, 1) branch strips the outer parens from
//    inline_flattened, leaving the bare object.
#[derive(Flow)]
struct InnerObj {
    x: i32,
}

#[derive(Flow)]
struct SingleFlatten {
    #[flow(flatten)]
    inner: InnerObj,
}

#[test]
fn single_flatten_only() {
    let c = cfg();
    let decl = SingleFlatten::decl(&c);
    assert!(decl.contains("type SingleFlatten"), "{decl}");
    assert!(decl.contains("x: number"), "{decl}");
    // Should NOT have intersection operator since there's only one flattened source
    assert!(!decl.contains("&"), "single flatten should not produce intersection: {decl}");
}
