//! Tests specifically targeting uncovered code paths for coverage.

#![allow(dead_code)]

use flowjs_rs::{Config, Flow};
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet, LinkedList, VecDeque};

// ── Export system coverage ──────────────────────────────────────────────

#[derive(Flow)]
struct ExportTarget {
    name: String,
    count: i32,
}

#[derive(Flow)]
struct ExportWithDeps {
    target: ExportTarget,
    tags: Vec<String>,
}

#[test]
fn export_to_string_includes_header_and_imports() {
    let cfg = Config::new();
    let content = ExportWithDeps::export_to_string(&cfg).unwrap();
    assert!(content.starts_with("// @flow"));
    assert!(content.contains("Generated by flowjs-rs"));
    assert!(content.contains("import type"));
    assert!(content.contains("ExportTarget"));
    assert!(content.contains("export type ExportWithDeps"));
}

#[test]
fn export_to_string_no_self_import() {
    let cfg = Config::new();
    let content = ExportTarget::export_to_string(&cfg).unwrap();
    assert!(!content.contains("import"), "should not import itself");
}

#[test]
fn export_all_writes_files() {
    let dir = std::env::temp_dir().join("flowjs_coverage_test");
    let _ = std::fs::remove_dir_all(&dir);
    let cfg = Config::new().with_out_dir(&dir);
    ExportWithDeps::export_all(&cfg).unwrap();

    // Both the type and its dependency should be exported
    assert!(dir.join("ExportWithDeps.js.flow").exists());
    assert!(dir.join("ExportTarget.js.flow").exists());

    // Check content
    let content = std::fs::read_to_string(dir.join("ExportWithDeps.js.flow")).unwrap();
    assert!(content.contains("export type ExportWithDeps"));

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn export_single_type() {
    let dir = std::env::temp_dir().join(format!("flowjs_cov_single_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let cfg = Config::new().with_out_dir(&dir);
    ExportTarget::export(&cfg).unwrap();
    assert!(dir.join("ExportTarget.js.flow").exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn export_idempotent() {
    let dir = std::env::temp_dir().join(format!("flowjs_cov_idempotent_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let cfg = Config::new().with_out_dir(&dir);
    ExportTarget::export(&cfg).unwrap();
    ExportTarget::export(&cfg).unwrap();
    let _ = std::fs::remove_dir_all(&dir);
}

// ── Config coverage ─────────────────────────────────────────────────────

#[test]
fn config_from_env() {
    let cfg = Config::from_env();
    // Just verify it doesn't panic and returns sane defaults
    assert!(!cfg.out_dir().as_os_str().is_empty());
    assert!(cfg.array_tuple_limit() > 0);
    assert!(!cfg.file_extension().is_empty());
    assert!(!cfg.large_int().is_empty());
}

#[test]
fn config_builder() {
    let cfg = Config::new()
        .with_out_dir("/tmp/test")
        .with_array_tuple_limit(32)
        .with_file_extension("mjs.flow")
        .with_large_int("number");
    assert_eq!(cfg.out_dir().to_str().unwrap(), "/tmp/test");
    assert_eq!(cfg.array_tuple_limit(), 32);
    assert_eq!(cfg.file_extension(), "mjs.flow");
    assert_eq!(cfg.large_int(), "number");
}

#[test]
fn config_resolve_output_path_no_extension() {
    let cfg = Config::new();
    let resolved = cfg.resolve_output_path(std::path::Path::new("Foo"));
    assert_eq!(resolved.to_str().unwrap(), "Foo.js.flow");
}

#[test]
fn config_resolve_output_path_with_extension() {
    let cfg = Config::new();
    let resolved = cfg.resolve_output_path(std::path::Path::new("custom/Foo.mjs.flow"));
    assert_eq!(resolved.to_str().unwrap(), "custom/Foo.mjs.flow");
}

// ── Impl coverage: exercise name/inline/dependencies for all types ──────

#[test]
fn all_collection_names() {
    let cfg = Config::new();
    assert!(Vec::<String>::name(&cfg).contains("$ReadOnlyArray"));
    assert!(HashSet::<i32>::name(&cfg).contains("$ReadOnlyArray"));
    assert!(BTreeSet::<i32>::name(&cfg).contains("$ReadOnlyArray"));
    assert!(VecDeque::<i32>::name(&cfg).contains("$ReadOnlyArray"));
    assert!(LinkedList::<i32>::name(&cfg).contains("$ReadOnlyArray"));
    assert!(HashMap::<String, i32>::name(&cfg).contains("[key:"));
    assert!(BTreeMap::<String, i32>::name(&cfg).contains("[key:"));
}

#[test]
fn all_collection_inlines() {
    let cfg = Config::new();
    assert!(Vec::<String>::inline(&cfg).contains("$ReadOnlyArray"));
    assert!(HashMap::<String, i32>::inline(&cfg).contains("[key:"));
}

#[test]
fn option_name_and_inline() {
    let cfg = Config::new();
    assert_eq!(Option::<String>::name(&cfg), "?string");
    assert_eq!(Option::<String>::inline(&cfg), "?string");
    assert!(Option::<String>::IS_OPTION);
}

#[test]
fn result_name_and_inline() {
    let cfg = Config::new();
    let name = Result::<String, i32>::name(&cfg);
    assert!(name.contains("Ok"));
    assert!(name.contains("Err"));
}

#[test]
fn tuple_names() {
    let cfg = Config::new();
    assert_eq!(<(String, i32)>::name(&cfg), "[string, number]");
    assert_eq!(<(bool,)>::name(&cfg), "[boolean]");
    assert_eq!(<(String, i32, bool)>::name(&cfg), "[string, number, boolean]");
}

#[test]
fn fixed_array_small_vs_large() {
    let cfg = Config::new();
    // Small array: tuple
    let small = <[i32; 3]>::name(&cfg);
    assert_eq!(small, "[number, number, number]");
    // Large array: $ReadOnlyArray
    let large = <[i32; 100]>::name(&cfg);
    assert!(large.contains("$ReadOnlyArray"));
}

#[test]
fn wrapper_types_are_transparent() {
    let cfg = Config::new();
    assert_eq!(Box::<String>::name(&cfg), "string");
    assert_eq!(std::sync::Arc::<i32>::name(&cfg), "number");
    assert_eq!(std::rc::Rc::<bool>::name(&cfg), "boolean");
    assert_eq!(std::cell::Cell::<f64>::name(&cfg), "number");
    assert_eq!(std::cell::RefCell::<String>::name(&cfg), "string");
    assert_eq!(std::sync::Mutex::<i32>::name(&cfg), "number");
    assert_eq!(std::sync::RwLock::<bool>::name(&cfg), "boolean");
    assert_eq!(std::num::Wrapping::<u32>::name(&cfg), "number");
    assert_eq!(std::num::Saturating::<u32>::name(&cfg), "number");
}

#[test]
fn reference_types_are_transparent() {
    let cfg = Config::new();
    assert_eq!(<&str>::name(&cfg), "string");
    assert_eq!(<&String>::name(&cfg), "string");
}

#[test]
fn cow_is_transparent() {
    let cfg = Config::new();
    assert_eq!(std::borrow::Cow::<str>::name(&cfg), "string");
}

#[test]
fn string_like_types() {
    let cfg = Config::new();
    assert_eq!(std::path::PathBuf::name(&cfg), "string");
    assert_eq!(std::path::Path::name(&cfg), "string");
    assert_eq!(std::time::SystemTime::name(&cfg), "string");
    assert_eq!(std::net::IpAddr::name(&cfg), "string");
    assert_eq!(std::net::Ipv4Addr::name(&cfg), "string");
    assert_eq!(std::net::Ipv6Addr::name(&cfg), "string");
    assert_eq!(std::net::SocketAddr::name(&cfg), "string");
    assert_eq!(std::net::SocketAddrV4::name(&cfg), "string");
    assert_eq!(std::net::SocketAddrV6::name(&cfg), "string");
}

#[test]
fn large_int_types() {
    let cfg = Config::new();
    assert_eq!(i64::name(&cfg), "bigint");
    assert_eq!(u64::name(&cfg), "bigint");
    assert_eq!(i128::name(&cfg), "bigint");
    assert_eq!(u128::name(&cfg), "bigint");

    let cfg_number = Config::new().with_large_int("number");
    assert_eq!(i64::name(&cfg_number), "number");
}

#[test]
fn nonzero_types() {
    let cfg = Config::new();
    assert_eq!(std::num::NonZeroU8::name(&cfg), "number");
    assert_eq!(std::num::NonZeroU16::name(&cfg), "number");
    assert_eq!(std::num::NonZeroU32::name(&cfg), "number");
    assert_eq!(std::num::NonZeroU64::name(&cfg), "bigint");
    assert_eq!(std::num::NonZeroI32::name(&cfg), "number");
    assert_eq!(std::num::NonZeroI64::name(&cfg), "bigint");
}

#[test]
fn range_duration_types() {
    let cfg = Config::new();
    let range = std::ops::Range::<i32>::name(&cfg);
    assert!(range.contains("start"));
    assert!(range.contains("end"));

    let dur = std::time::Duration::name(&cfg);
    assert!(dur.contains("secs"));
    assert!(dur.contains("nanos"));
}

#[test]
fn phantom_data_is_void() {
    let cfg = Config::new();
    assert_eq!(std::marker::PhantomData::<String>::name(&cfg), "void");
}

#[test]
fn infallible_is_empty() {
    let cfg = Config::new();
    assert_eq!(std::convert::Infallible::name(&cfg), "empty");
}

#[test]
fn fn_pointer_names() {
    let cfg = Config::new();
    let f0 = <fn() -> String>::name(&cfg);
    assert_eq!(f0, "() => string");
    let f1 = <fn(i32) -> bool>::name(&cfg);
    assert!(f1.contains("arg0: number"));
    assert!(f1.contains("=> boolean"));
    let f2 = <fn(String, i32) -> ()>::name(&cfg);
    assert!(f2.contains("arg0: string"));
    assert!(f2.contains("arg1: number"));
}

// ── Dependencies coverage ───────────────────────────────────────────────

#[test]
fn dependencies_collected() {
    let cfg = Config::new();
    let deps = ExportWithDeps::dependencies(&cfg);
    let dep_names: Vec<&str> = deps.iter().map(|d| d.flow_name.as_str()).collect();
    assert!(dep_names.contains(&"ExportTarget"), "should list ExportTarget as dependency");
}

// ── Trait method coverage ───────────────────────────────────────────────

#[test]
fn ident_strips_generics() {
    let cfg = Config::new();
    assert_eq!(Vec::<String>::ident(&cfg), "$ReadOnlyArray");
}

#[test]
fn is_enum_flag() {
    assert!(!ExportTarget::IS_ENUM);
    assert!(!ExportTarget::IS_OPTION);
}

#[test]
fn decl_concrete() {
    let cfg = Config::new();
    let decl = ExportTarget::decl_concrete(&cfg);
    assert!(decl.contains("type ExportTarget"));
}
